### ISSUE TITLE
Yay!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s3-evaluacion-intermedia-katherinebl#1]
Well done, @katherinebl 

Here you have some tips to improve the exercise:

- [x] Follow the [GHP publishing instructions](https://books.adalab.es/materiales-front-end-e/sprint-3.-es6-y-react/3_4_intro_react_2#publicar-nuestra-app-react-en-github-pages)
- [x] Use the App.js state to save the main array
- [x] Use the second exercise component
- [x] solve the console errors ;)
- [x] Use PropTypes

This time you have a deadline: 16-1-2019

**Comment by katherinebl** [comment]
Fixed issues :)
